### ISSUE TITLE
[Question] Does this have to be asynchronous?

### ISSUE THREAD

**Issue by aizkhaj** [ovhemert/pino-applicationinsights#12]
I'm using `pino-multi-stream` to create transports for papertrail (using your other plugin `pino-papertrail`) and Azure Application Insights (`pino-applicationinsights`).

I noticed that in your API docs you are using `await insights.createWriteStream()`, but not in context of an async function. Is the use of `createWriteStream` as an async function necessary here? TelemetryAPI on Azure docs aren't referencing use of async either.

My current logger configuration is not an async function and so my linter is complaining about the use of await outside an async function. My understanding is that it would be bad practice.

Sorry if I come across as ignorant, I come in peace. I'm learning along the way and attempting to implement Pino for use, would appreciate your insight into `insights`:

From the context of your API docs, are you recommending we stick to using `await insights.createWriteStream()` outside an async function because you wrote `createWriteStream` as an async function or is there another reason related to Azure Insights that I'm unaware of?

Thanks for your open source work, I appreciate it.

**Comment by ovhemert** [comment]
The `await` that you see in the example code, is just for readability. You would use it that way if you are writing functions with `async/await`. But actually, these functions are promises, the async/await is just another (more clean) way to write Promises.

If your own function is not an async-function, you could call `createWriteStream`, just like any other promise.

```js
// create the Azure Application Insights destination stream
const writeStream = await insights.createWriteStream()
```

would become:

```js
// create the Azure Application Insights destination stream
insights.createWriteStream().then(writeStream => {
  // ... do something with writeStream
})
```

Hope that helps you out with your question.

**Comment by aizkhaj** [comment]
Sorry if I miscommunicated and I really appreciate the response, but I understand the usage of `async/await` just not why we need the Promisified function in the first place. Is it to do with Azure Insights wanting it that way or was it a decision you made to try and make it more of a sequential logging process to Insights?

(Trying to debug my logging so that I can get azure insights working that's all 😄).

**Comment by ovhemert** [comment]
Ah,.. I see what you mean. Yes, in the past I had to call some Azure Insights configuration functions that required a callback. This made the function async. At the moment the configuration function is gone, but to keep backwards compatibility (and possible implementation of async calls in the future), the Promise/async remains.
